services:
  wuzapi-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_FQDN_WUZAPI_8000
      - WUZAPI_ADMIN_TOKEN=$SERVICE_PASSWORD_ADMIN
      - WUZAPI_GLOBAL_ENCRYPTION_KEY=$SERVICE_PASSWORD_ENCRYPTIONKEY
      - WUZAPI_GLOBAL_HMAC_KEY=${WUZAPI_GLOBAL_HMAC_KEY:-}
      - WUZAPI_GLOBAL_WEBHOOK=${WUZAPI_GLOBAL_WEBHOOK:-}
      - DB_USER=$SERVICE_USER_DB
      - DB_PASSWORD=$SERVICE_PASSWORD_DB
      - DB_NAME=${DB_NAME:-wuzapi}
      - DB_HOST=db
      - DB_PORT=${DB_PORT:-5432}
      - TZ=${TZ:-America/Sao_Paulo}
      - WEBHOOK_FORMAT=${WEBHOOK_FORMAT:-json}
      - SESSION_DEVICE_NAME=${SESSION_DEVICE_NAME:-CursoGameDev}
      # RabbitMQ configuration Optional
      - RABBITMQ_URL=amqp://$SERVICE_USER_RABBITMQ:$SERVICE_PASSWORD_RABBITMQ@rabbitmq:5672/
      - RABBITMQ_QUEUE=whatsapp_events
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: $SERVICE_USER_DB
      POSTGRES_PASSWORD: $SERVICE_PASSWORD_DB
      POSTGRES_DB: ${DB_NAME:-wuzapi}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-wuzapi}"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      SERVICE_FQDN_RABBITMQ_15672: null
      RABBITMQ_DEFAULT_USER: $SERVICE_USER_RABBITMQ
      RABBITMQ_DEFAULT_PASS: $SERVICE_PASSWORD_RABBITMQ
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  db_data:
  rabbitmq_data:
